server:
  port: 9999

springdoc:
  swagger-ui:
    path: /swagger.html

spring:
  kafka:
    bootstrap-servers: localhost:29092
    producer:
      topic: order-event
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      retries: 3
      acks: 1
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:file:C:/kafka/h2/orderdb;AUTO_SERVER=TRUE
    username: sa
    password: 
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
      path: /h2-console
